#ifndef WRAPPER_EXPORT_H
#define WRAPPER_EXPORT_H

#if defined(WRAPPER_EXPORT_SYMBOLS)
#  define WRAPPER_DLL_EXPORT Q_DECL_EXPORT
#else
#  define WRAPPER_DLL_EXPORT Q_DECL_IMPORT
#endif

#endif // WRAPPER_EXPORT_H
